dist: bionic

language: php

php:
  - 7.3

cache:
  directories:
    - app/node_modules
    - app/vendor

before_script:
  - cd ./app/
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - npm install
  - php artisan key:generate

script:
  - npm run lint
  - vendor/bin/phpunit
