version: '3'
services:
  ukrsib:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes: 
      - ./app:/var/www/htdocs/
    working_dir: /var/www/htdocs
    restart: always
  web:
    image: nginx:alpine
    ports:
      - 10080:80
    volumes:
      - ./app:/var/www/htdocs/
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ukrsib
    restart: always 