version: '3'
services:
  laravel:
    build:
      context: ./
      dockerfile: laravel.dockerfile
      args:
        - WITH_XDEBUG=true
    env_file: .env
    volumes: 
      - ./htdocs:/var/www/htdocs/
    working_dir: /var/www/htdocs
  web:
    image: nginx:alpine
    ports:
      - 10080:80
      - 10443:443
    volumes:
      - ./htdocs:/var/www/htdocs/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
  db:
    image: mariadb:10.4
    ports:
      - 13306:3306
    restart: always
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=laravel
      - MYSQL_USER=laravel
      - MYSQL_USER_PASSWORD=laravel
    volumes:
      - ./.mariadb:/var/lib/mysql