version: '3'
services:
  laravel:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        - WITH_XDEBUG=true
    env_file: .env
    volumes:
      - ./app:/var/www/htdocs/
    working_dir: /var/www/htdocs
  web:
    image: nginx:alpine
    ports:
      - 10080:80
    volumes:
      - ./app:/var/www/htdocs/
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
  composer:
    image: composer:latest
    volumes:
      - ./app:/app
    command:
      - install
    depends_on:
      - laravel
