version: '3'
services:
  laravel:
    build:
      context: ./
      dockerfile: laravel.dockerfile
    volumes: 
      - ./htdocs:/var/www/htdocs/
    working_dir: /var/www/htdocs
  web:
    image: nginx:alpine
    ports:
      - 80
      - 443
    volumes:
      - ./htdocs:/var/www/htdocs/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
  db:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=laravel
      - MYSQL_USER=laravel
      - MYSQL_USER_PASSWORD=laravel
    volumes:
      - ./laravel.sql.gz:/docker-entrypoint-initdb.d/laravel.sql.gz

